title: Amrita Raychaudhury
description: Motivated for industrial innovation and digital transformation
[Email](amrita.raychaudhury@rwth-aachen.de) [LinkedIn](https://www.linkedin.com/in/amritaraychaudhury/)
theme: jekyll-theme-CAYMAN
